local_backend: true

backend:
  name: git-gateway
media_folder: '_media/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    publish_mode: editorial_workflow
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Categories', name: 'categories', widget: 'string' }
      - { label: 'Author', name: 'author', widget: "relation", collection: "authors", search_fields: ["shortname"], value_field: "shortname", display_fields: ["shortname", "display_name"] }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'authors'
    label: 'Authors'
    folder: '_authors/'
    create: true
    slug: '{{shortname}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'author' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Short Name', name: 'shortname', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: 'Photo', name: 'image', widget: 'image' }
      - { label: 'Description (short)', name: 'description', widget: 'string' }
      - { label: 'About', name: 'body', widget: 'markdown' }
  - name: 'config'
    label: 'Config'
    editor:
      preview: false
    files:
      - label: 'Navigation'
        name: 'navigation'
        file: '_data/navigation.yml'
        fields:
          - label: 'Navigation Items'
            name: 'items'
            widget: 'list'
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Link, name: link, widget: string }
      - label: 'Featured Post'
        name: 'fp'
        file: '_data/featured.yml'
        fields:
          - label: 'Post'
            name: 'post'
            widget: "relation"
            collection: "blog"
            search_fields: ["title"]
            value_field: "title"
            display_fields: ["title"]
      - label: 'About'
        name: 'about'
        file: 'about.markdown'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'default' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }